### ISSUE TITLE
Remaining type-class instances

### ISSUE THREAD

**Issue by tonymorris** [qfpl/exitcode#2]
* [x] `MonadReader`
* [x] `MonadWriter`
* [x] `MonadState`
* [x] `MonadRWS`
* [x] `MonadError`
* [ ] ~~`MonadFix`~~ (would result in partial function)
* [ ] ~~`MonadFail`~~ (lacks a sensible instance because `Either` - see [`MonadFail` proposal](https://prime.haskell.org/wiki/Libraries/Proposals/MonadFail)
* [x] `MonadCont`
* [ ] ~~`Foldable1`~~ (impossible due to Either)
* [ ] ~~`Traversable1`~~ (impossible due to Either)
* [x] `MonadTrans`
* [ ] ~~`MonadZip`~~ (would fail information preservation law)
* [x] `Eq1`
* [x] `Ord1`
* [x] `Show1`

**Comment by tonymorris** [comment]
* [ ] `MMonad`
* [ ] `MFunctor`

https://hackage.haskell.org/package/mmorph

**Comment by ajmcmiddlin** [comment]
`ExceptT` does have a [`MonadFix` instance](https://hackage.haskell.org/package/transformers-0.5.4.0/docs/src/Control.Monad.Trans.Except.html#line-237), but it's partial. Let's not be partial.

**Comment by tonymorris** [comment]
:+1:

**Comment by tonymorris** [comment]
`mmorph`

8e36270c1f26320a7c6a7207c808418cba7af73d
